### ISSUE TITLE
Odd random crashes 

### ISSUE THREAD

**Issue by Drakoflame** [CreativeMD/ItemPhysic#27]
http://pastebin.com/JCAx1d5j this is with Underground Biomes constructs
http://pastebin.com/GETLxDQb without UBC, issue happened when a block of congeiled slime fell into some liquid slime

http://pastebin.com/bpW1H1ds this was durring startup with another mod called Up Down and All Around

**Comment by Mysteryem** [comment]
To expand upon the second crash log involving my mod (Up And Down And All Around) and the crash log I found at https://minecraft.curseforge.com/projects/better-with-mods?page=6#c209

I would guess that you are modifying `EntityItem` such that subclasses of it no longer work properly.

In the linked crash log on curseforge, you can see the `betterwithmods.entity.item.EntityItemBuoy.superSearchForOtherItemsNearby(EntityItemBuoy.java:57)` stack frame before heading towards the `native` method `java.lang.Class.getDeclaredMethods0` that throws the exception.

Furthermore, in the crash log with my mod included (http://pastebin.com/bpW1H1ds), you can see `uk.co.mysterymayhem.gravitymod.CommonProxy.registerListeners(CommonProxy.java:63)` before the `native` method goes and throws an exception. 

On line 63 of my `CommonProxy` class, I'm registering `EntityFloatingItem.class` (an `EntityItem` subclass) to the event manager: https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/754c84642468d265b2963e32ec9adf4f9b227621/src/main/java/uk/co/mysterymayhem/gravitymod/CommonProxy.java#L63

If useful, the entire `EntityFloatingItem` class can be found at https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/754c84642468d265b2963e32ec9adf4f9b227621/src/main/java/uk/co/mysterymayhem/gravitymod/common/entities/EntityFloatingItem.java

**Comment by CreativeMD** [comment]
Ok ... this crash is really weird, but i think i found the problem. Seems to be an issue by my name transformer. Could test if this file fixes all of the issues for you?

https://www.dropbox.com/s/om709id6vz8y2fa/CreativeCore%20v1.6.18%20mc1.10.2.jar?dl=1

**Comment by CreativeMD** [comment]
Uploaded v1.6.19 which should fix this issue. Thanks for reporting and helping me to find this nasty bug.

**Comment by Mysteryem** [comment]
Not getting an EntityItem related crash with v1.6.19, looks like that bug is fixed.

**Comment by CreativeMD** [comment]
Nice to hear that. Again thanks for helping out.

**Comment by Drakoflame** [comment]
hurray for teamwork! Hopefully this also helps with the issues involving the crashes with UBC and Tinkers. IT seems like they're all somehow related one way or another. I'll go test it now, hopefully it solves those weird issues. I guess the other fix would be to simply remove Item Physics, as that seems to be the issue.

In the event that I still get the same crashes as the ones with Tinkers and UBC, I will come back and open up a new thread with any crashes I get. Thanks once again Creative and Mysteryem!
